// mangos-angular/mangOS-admin-main/src/app/core/ais/zoho-crm/zoho-crm.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ZohoCrmService, ZohoContact, ZohoLead, ZohoDeal } from '../services/zoho-crm.service';

@Component({
  selector: 'app-zoho-crm',
  templateUrl: './zoho-crm.component.html',
  styleUrls: ['./zoho-crm.component.scss']
})
export class ZohoCrmComponent implements OnInit {
  @ViewChild(MatPaginator) paginator!: MatPaginator;
  @ViewChild(MatSort) sort!: MatSort;

  // Authentication state
  isAuthenticated = false;
  isLoading = false;

  // Tab management
  selectedTabIndex = 0;

  // Data sources for different modules
  contactsDataSource = new MatTableDataSource<ZohoContact>([]);
  leadsDataSource = new MatTableDataSource<ZohoLead>([]);
  dealsDataSource = new MatTableDataSource<ZohoDeal>([]);

  // Table columns
  contactColumns = ['First_Name', 'Last_Name', 'Email', 'Phone', 'Account_Name', 'Created_Time', 'actions'];
  leadColumns = ['First_Name', 'Last_Name', 'Email', 'Company', 'Lead_Status', 'Created_Time', 'actions'];
  dealColumns = ['Deal_Name', 'Account_Name', 'Stage', 'Amount', 'Closing_Date', 'actions'];

  // Statistics
  stats = {
    totalContacts: 0,
    totalLeads: 0,
    totalDeals: 0,
    totalRevenue: 0
  };

  constructor(
    private zohoCrmService: ZohoCrmService,
    private route: ActivatedRoute,
    private router: Router,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit(): void {
    this.checkAuthentication();
    this.handleOAuthCallback();
  }

  private checkAuthentication(): void {
    this.isAuthenticated = this.zohoCrmService.isAuthenticated();
    if (this.isAuthenticated) {
      this.loadAllData();
    }
  }

  private handleOAuthCallback(): void {
    this.route.queryParams.subscribe(params => {
      if (params['code']) {
        this.exchangeCodeForToken(params['code']);
      }
    });
  }

  // Authentication Methods
  connectToZoho(): void {
    const authUrl = this.zohoCrmService.getAuthorizationUrl();
    window.location.href = authUrl;
  }

  private exchangeCodeForToken(code: string): void {
    this.isLoading = true;
    this.zohoCrmService.exchangeCodeForToken(code).subscribe({
      next: (response) => {
        if (response.access_token) {
          this.zohoCrmService.setAccessToken(response.access_token);
          if (response.refresh_token) {
            localStorage.setItem('zoho_refresh_token', response.refresh_token);
          }
          this.isAuthenticated = true;
          this.loadAllData();
          this.snackBar.open('Successfully connected to Zoho CRM!', 'Close', { duration: 3000 });
          // Clean up URL
          this.router.navigate(['/ais/zoho-crm'], { replaceUrl: true });
        }
        this.isLoading = false;
      },
      error: (error) => {
        console.error('OAuth error:', error);
        this.snackBar.open('Failed to connect to Zoho CRM. Please try again.', 'Close', { duration: 5000 });
        this.isLoading = false;
      }
    });
  }

  disconnect(): void {
    this.zohoCrmService.logout();
    this.isAuthenticated = false;
    this.contactsDataSource.data = [];
    this.leadsDataSource.data = [];
    this.dealsDataSource.data = [];
    this.resetStats();
    this.snackBar.open('Disconnected from Zoho CRM', 'Close', { duration: 3000 });
  }

  // Data Loading Methods
  private loadAllData(): void {
    this.loadContacts();
    this.loadLeads();
    this.loadDeals();
  }

  loadContacts(): void {
    this.isLoading = true;
    this.zohoCrmService.getContacts().subscribe({
      next: (response) => {
        if (response.data) {
          this.contactsDataSource.data = response.data;
          this.stats.totalContacts = response.data.length;
        }
        this.isLoading = false;
      },
      error: (error) => {
        console.error('Error loading contacts:', error);
        this.handleApiError(error);
        this.isLoading = false;
      }
    });
  }

  loadLeads(): void {
    this.zohoCrmService.getLeads().subscribe({
      next: (response) => {
        if (response.data) {
          this.leadsDataSource.data = response.data;
          this.stats.totalLeads = response.data.length;
        }
      },
      error: (error) => {
        console.error('Error loading leads:', error);
        this.handleApiError(error);
      }
    });
  }

  loadDeals(): void {
    this.zohoCrmService.getDeals().subscribe({
      next: (response) => {
        if (response.data) {
          this.dealsDataSource.data = response.data;
          this.stats.totalDeals = response.data.length;
          this.stats.totalRevenue = response.data.reduce((sum: number, deal: any) => sum + (deal.Amount || 0), 0);
        }
      },
      error: (error) => {
        console.error('Error loading deals:', error);
        this.handleApiError(error);
      }
    });
  }

  // CRUD Operations
  createContact(): void {
    // This would open a dialog for creating a new contact
    this.snackBar.open('Create Contact feature coming soon!', 'Close', { duration: 3000 });
  }

  editContact(contact: ZohoContact): void {
    // This would open a dialog for editing the contact
    this.snackBar.open(`Edit Contact: ${contact.First_Name} ${contact.Last_Name}`, 'Close', { duration: 3000 });
  }

  deleteContact(contact: ZohoContact): void {
    if (confirm(`Are you sure you want to delete ${contact.First_Name} ${contact.Last_Name}?`)) {
      if (contact.id) {
        this.zohoCrmService.deleteContact(contact.id).subscribe({
          next: () => {
            this.loadContacts();
            this.snackBar.open('Contact deleted successfully', 'Close', { duration: 3000 });
          },
          error: (error) => {
            console.error('Error deleting contact:', error);
            this.handleApiError(error);
          }
        });
      }
    }
  }

  // Utility Methods
  private handleApiError(error: any): void {
    if (error.status === 401) {
      this.snackBar.open('Authentication expired. Please reconnect to Zoho CRM.', 'Close', { duration: 5000 });
      this.disconnect();
    } else {
      this.snackBar.open('An error occurred. Please try again.', 'Close', { duration: 3000 });
    }
  }

  private resetStats(): void {
    this.stats = {
      totalContacts: 0,
      totalLeads: 0,
      totalDeals: 0,
      totalRevenue: 0
    };
  }

  // Search functionality
  applyFilter(event: Event, dataSource: MatTableDataSource<any>): void {
    const filterValue = (event.target as HTMLInputElement).value;
    dataSource.filter = filterValue.trim().toLowerCase();

    if (dataSource.paginator) {
      dataSource.paginator.firstPage();
    }
  }

  // Tab change handler
  onTabChange(index: number): void {
    this.selectedTabIndex = index;
  }

  // Refresh data
  refreshData(): void {
    if (this.isAuthenticated) {
      this.loadAllData();
      this.snackBar.open('Data refreshed successfully', 'Close', { duration: 2000 });
    }
  }

  // Helper methods for chip colors
  getLeadStatusColor(status: string): string {
    switch (status?.toLowerCase()) {
      case 'qualified': return 'primary';
      case 'contacted': return 'accent';
      case 'new': return 'info';
      case 'working': return 'warn';
      default: return 'primary';
    }
  }

  getDealStageColor(stage: string): string {
    switch (stage?.toLowerCase()) {
      case 'closed won': return 'success';
      case 'closed lost': return 'warn';
      case 'proposal': return 'accent';
      case 'negotiation': return 'primary';
      default: return 'info';
    }
  }
}
<div class="zoho-crm-container">
  <!-- Header Section -->
  <div class="header-section">
    <div class="title-section">
      <h1>
        <mat-icon>business</mat-icon>
        Zoho CRM Integration
      </h1>
      <p class="subtitle">Manage your customer relationships seamlessly within MangOS</p>
    </div>
    
    <div class="action-buttons">
      <button mat-raised-button color="primary" (click)="refreshData()" *ngIf="isAuthenticated" [disabled]="isLoading">
        <mat-icon>refresh</mat-icon>
        Refresh
      </button>
      
      <button mat-raised-button color="accent" (click)="connectToZoho()" *ngIf="!isAuthenticated" [disabled]="isLoading">
        <mat-icon>link</mat-icon>
        Connect to Zoho CRM
      </button>
      
      <button mat-raised-button color="warn" (click)="disconnect()" *ngIf="isAuthenticated">
        <mat-icon>link_off</mat-icon>
        Disconnect
      </button>
    </div>
  </div>

  <!-- Loading Spinner -->
  <div class="loading-container" *ngIf="isLoading">
    <mat-spinner></mat-spinner>
    <p>Loading Zoho CRM data...</p>
  </div>

  <!-- Authentication Required -->
  <div class="auth-required" *ngIf="!isAuthenticated && !isLoading">
    <mat-card class="auth-card">
      <mat-card-header>
        <mat-card-title>
          <mat-icon>security</mat-icon>
          Authentication Required
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <p>To access Zoho CRM features, you need to connect your Zoho account with MangOS.</p>
        <ul>
          <li>Secure OAuth 2.0 authentication</li>
          <li>Access to your Contacts, Leads, and Deals</li>
          <li>Real-time synchronization</li>
          <li>Full CRUD operations</li>
        </ul>
      </mat-card-content>
      <mat-card-actions>
        <button mat-raised-button color="primary" (click)="connectToZoho()">
          <mat-icon>link</mat-icon>
          Connect Now
        </button>
      </mat-card-actions>
    </mat-card>
  </div>

  <!-- Main Content - Dashboard -->
  <div class="main-content" *ngIf="isAuthenticated && !isLoading">
    
    <!-- Statistics Cards -->
    <div class="stats-section">
      <mat-card class="stat-card contacts">
        <mat-card-content>
          <div class="stat-content">
            <mat-icon>contacts</mat-icon>
            <div class="stat-info">
              <h3>{{stats.totalContacts}}</h3>
              <p>Total Contacts</p>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <mat-card class="stat-card leads">
        <mat-card-content>
          <div class="stat-content">
            <mat-icon>person_add</mat-icon>
            <div class="stat-info">
              <h3>{{stats.totalLeads}}</h3>
              <p>Active Leads</p>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <mat-card class="stat-card deals">
        <mat-card-content>
          <div class="stat-content">
            <mat-icon>handshake</mat-icon>
            <div class="stat-info">
              <h3>{{stats.totalDeals}}</h3>
              <p>Open Deals</p>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <mat-card class="stat-card revenue">
        <mat-card-content>
          <div class="stat-content">
            <mat-icon>attach_money</mat-icon>
            <div class="stat-info">
              <h3>${{stats.totalRevenue | number:'1.0-0'}}</h3>
              <p>Total Revenue</p>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>

    <!-- Tabs Section -->
    <mat-card class="data-card">
      <mat-tab-group (selectedTabChange)="onTabChange($event.index)">
        
        <!-- Contacts Tab -->
        <mat-tab label="Contacts" [badge]="stats.totalContacts">
          <ng-template mat-tab-label>
            <mat-icon>contacts</mat-icon>
            Contacts
            <mat-chip-list>
              <mat-chip color="primary" selected>{{stats.totalContacts}}</mat-chip>
            </mat-chip-list>
          </ng-template>
          
          <div class="tab-content">
            <div class="tab-header">
              <mat-form-field appearance="outline" class="search-field">
                <mat-label>Search Contacts</mat-label>
                <input matInput (keyup)="applyFilter($event, contactsDataSource)" placeholder="Search by name, email...">
                <mat-icon matSuffix>search</mat-icon>
              </mat-form-field>
              
              <button mat-raised-button color="primary" (click)="createContact()">
                <mat-icon>add</mat-icon>
                Add Contact
              </button>
            </div>

            <div class="table-container">
              <table mat-table [dataSource]="contactsDataSource" matSort class="data-table">
                <ng-container matColumnDef="First_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>First Name</th>
                  <td mat-cell *matCellDef="let contact">{{contact.First_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Last_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Last Name</th>
                  <td mat-cell *matCellDef="let contact">{{contact.Last_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Email">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Email</th>
                  <td mat-cell *matCellDef="let contact">
                    <a href="mailto:{{contact.Email}}" class="email-link">{{contact.Email}}</a>
                  </td>
                </ng-container>

                <ng-container matColumnDef="Phone">
                  <th mat-header-cell *matHeaderCellDef>Phone</th>
                  <td mat-cell *matCellDef="let contact">{{contact.Phone || 'N/A'}}</td>
                </ng-container>

                <ng-container matColumnDef="Account_Name">
                  <th mat-header-cell *matHeaderCellDef>Company</th>
                  <td mat-cell *matCellDef="let contact">{{contact.Account_Name || 'N/A'}}</td>
                </ng-container>

                <ng-container matColumnDef="Created_Time">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Created</th>
                  <td mat-cell *matCellDef="let contact">{{contact.Created_Time | date:'short'}}</td>
                </ng-container>

                <ng-container matColumnDef="actions">
                  <th mat-header-cell *matHeaderCellDef>Actions</th>
                  <td mat-cell *matCellDef="let contact">
                    <button mat-icon-button color="primary" (click)="editContact(contact)" matTooltip="Edit">
                      <mat-icon>edit</mat-icon>
                    </button>
                    <button mat-icon-button color="warn" (click)="deleteContact(contact)" matTooltip="Delete">
                      <mat-icon>delete</mat-icon>
                    </button>
                  </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="contactColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: contactColumns;"></tr>
              </table>

              <mat-paginator [pageSizeOptions]="[10, 25, 50, 100]" showFirstLastButtons></mat-paginator>
            </div>
          </div>
        </mat-tab>

        <!-- Leads Tab -->
        <mat-tab label="Leads" [badge]="stats.totalLeads">
          <ng-template mat-tab-label>
            <mat-icon>person_add</mat-icon>
            Leads
            <mat-chip-list>
              <mat-chip color="accent" selected>{{stats.totalLeads}}</mat-chip>
            </mat-chip-list>
          </ng-template>
          
          <div class="tab-content">
            <div class="tab-header">
              <mat-form-field appearance="outline" class="search-field">
                <mat-label>Search Leads</mat-label>
                <input matInput (keyup)="applyFilter($event, leadsDataSource)" placeholder="Search by name, company...">
                <mat-icon matSuffix>search</mat-icon>
              </mat-form-field>
              
              <button mat-raised-button color="accent">
                <mat-icon>add</mat-icon>
                Add Lead
              </button>
            </div>

            <div class="table-container">
              <table mat-table [dataSource]="leadsDataSource" matSort class="data-table">
                <ng-container matColumnDef="First_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>First Name</th>
                  <td mat-cell *matCellDef="let lead">{{lead.First_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Last_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Last Name</th>
                  <td mat-cell *matCellDef="let lead">{{lead.Last_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Email">
                  <th mat-header-cell *matHeaderCellDef>Email</th>
                  <td mat-cell *matCellDef="let lead">
                    <a href="mailto:{{lead.Email}}" class="email-link">{{lead.Email}}</a>
                  </td>
                </ng-container>

                <ng-container matColumnDef="Company">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Company</th>
                  <td mat-cell *matCellDef="let lead">{{lead.Company}}</td>
                </ng-container>

                <ng-container matColumnDef="Lead_Status">
                  <th mat-header-cell *matHeaderCellDef>Status</th>
                  <td mat-cell *matCellDef="let lead">
                    <mat-chip [color]="getLeadStatusColor(lead.Lead_Status)" selected>
                      {{lead.Lead_Status || 'New'}}
                    </mat-chip>
                  </td>
                </ng-container>

                <ng-container matColumnDef="Created_Time">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Created</th>
                  <td mat-cell *matCellDef="let lead">{{lead.Created_Time | date:'short'}}</td>
                </ng-container>

                <ng-container matColumnDef="actions">
                  <th mat-header-cell *matHeaderCellDef>Actions</th>
                  <td mat-cell *matCellDef="let lead">
                    <button mat-icon-button color="primary" matTooltip="Edit">
                      <mat-icon>edit</mat-icon>
                    </button>
                    <button mat-icon-button color="accent" matTooltip="Convert to Deal">
                      <mat-icon>trending_up</mat-icon>
                    </button>
                  </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="leadColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: leadColumns;"></tr>
              </table>

              <mat-paginator [pageSizeOptions]="[10, 25, 50, 100]" showFirstLastButtons></mat-paginator>
            </div>
          </div>
        </mat-tab>

        <!-- Deals Tab -->
        <mat-tab label="Deals" [badge]="stats.totalDeals">
          <ng-template mat-tab-label>
            <mat-icon>handshake</mat-icon>
            Deals
            <mat-chip-list>
              <mat-chip color="warn" selected>{{stats.totalDeals}}</mat-chip>
            </mat-chip-list>
          </ng-template>
          
          <div class="tab-content">
            <div class="tab-header">
              <mat-form-field appearance="outline" class="search-field">
                <mat-label>Search Deals</mat-label>
                <input matInput (keyup)="applyFilter($event, dealsDataSource)" placeholder="Search by deal name, account...">
                <mat-icon matSuffix>search</mat-icon>
              </mat-form-field>
              
              <button mat-raised-button color="warn">
                <mat-icon>add</mat-icon>
                Add Deal
              </button>
            </div>

            <div class="table-container">
              <table mat-table [dataSource]="dealsDataSource" matSort class="data-table">
                <ng-container matColumnDef="Deal_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Deal Name</th>
                  <td mat-cell *matCellDef="let deal">{{deal.Deal_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Account_Name">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Account</th>
                  <td mat-cell *matCellDef="let deal">{{deal.Account_Name}}</td>
                </ng-container>

                <ng-container matColumnDef="Stage">
                  <th mat-header-cell *matHeaderCellDef>Stage</th>
                  <td mat-cell *matCellDef="let deal">
                    <mat-chip [color]="getDealStageColor(deal.Stage)" selected>
                      {{deal.Stage}}
                    </mat-chip>
                  </td>
                </ng-container>

                <ng-container matColumnDef="Amount">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Amount</th>
                  <td mat-cell *matCellDef="let deal" class="amount-cell">
                    ${{deal.Amount | number:'1.2-2'}}
                  </td>
                </ng-container>

                <ng-container matColumnDef="Closing_Date">
                  <th mat-header-cell *matHeaderCellDef mat-sort-header>Closing Date</th>
                  <td mat-cell *matCellDef="let deal">{{deal.Closing_Date | date:'mediumDate'}}</td>
                </ng-container>

                <ng-container matColumnDef="actions">
                  <th mat-header-cell *matHeaderCellDef>Actions</th>
                  <td mat-cell *matCellDef="let deal">
                    <button mat-icon-button color="primary" matTooltip="Edit">
                      <mat-icon>edit</mat-icon>
                    </button>
                    <button mat-icon-button color="accent" matTooltip="View Details">
                      <mat-icon>visibility</mat-icon>
                    </button>
                  </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="dealColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: dealColumns;"></tr>
              </table>

              <mat-paginator [pageSizeOptions]="[10, 25, 50, 100]" showFirstLastButtons></mat-paginator>
            </div>
          </div>
        </mat-tab>

      </mat-tab-group>
    </mat-card>
  </div>
</div>

// Frontend-master/Frontend-master/src/pages/Admin/ZohoCRM.tsx
// Zoho CRM Integration Component - Clean build version
import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  IconButton,
  TextField,
  InputAdornment,
  Tabs,
  Tab,
  CircularProgress,
  Alert,
} from '@mui/material';
import {
  Business,
  PersonAdd,
  Handshake,
  AttachMoney,
  Search,
  Edit,
  Delete,
  Refresh,
  Link,
  LinkOff,
} from '@mui/icons-material';
import zohoCrmService, { ZohoContact, ZohoLead, ZohoDeal } from '../../services/zohoCrmService';

interface Stats {
  totalContacts: number;
  totalLeads: number;
  totalDeals: number;
  totalRevenue: number;
}

const ZohoCRM: React.FC = () => {
  // State management
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedTab, setSelectedTab] = useState(0);
  const [error, setError] = useState<string>('');
  
  // Data states
  const [contacts, setContacts] = useState<ZohoContact[]>([]);
  const [leads, setLeads] = useState<ZohoLead[]>([]);
  const [deals, setDeals] = useState<ZohoDeal[]>([]);
  const [stats, setStats] = useState<Stats>({
    totalContacts: 0,
    totalLeads: 0,
    totalDeals: 0,
    totalRevenue: 0
  });
  
  // Search states
  const [contactSearch, setContactSearch] = useState('');
  const [leadSearch, setLeadSearch] = useState('');
  const [dealSearch, setDealSearch] = useState('');

  useEffect(() => {
    checkAuthentication();
    handleOAuthCallback();
  }, []);

  const checkAuthentication = () => {
    const isAuth = zohoCrmService.isAuthenticated();
    setIsAuthenticated(isAuth);
    if (isAuth) {
      loadAllData();
    }
  };

  const handleOAuthCallback = () => {
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get('code');
    const error = urlParams.get('error');
    
    console.log('OAuth callback - code:', code, 'error:', error);
    
    if (error) {
      setError(`OAuth error: ${error}`);
      return;
    }
    
    if (code) {
      exchangeCodeForToken(code);
    }
  };

  const connectToZoho = () => {
    const authUrl = zohoCrmService.getAuthorizationUrl();
    window.location.href = authUrl;
  };

  const exchangeCodeForToken = async (code: string) => {
    setIsLoading(true);
    setError(''); // Clear any previous errors
    
    try {
      console.log('Exchanging code for token...');
      const response = await zohoCrmService.exchangeCodeForToken(code);
      console.log('Token exchange response:', response);
      
      if (response.access_token) {
        zohoCrmService.setAccessToken(response.access_token);
        if (response.refresh_token) {
          localStorage.setItem('zoho_refresh_token', response.refresh_token);
        }
        setIsAuthenticated(true);
        await loadAllData();
        // Clean up URL
        window.history.replaceState({}, document.title, window.location.pathname);
      } else {
        throw new Error('No access token received');
      }
    } catch (error) {
      console.error('OAuth error:', error);
      setError(`Failed to connect to Zoho CRM: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setIsLoading(false);
    }
  };

  const disconnect = () => {
    zohoCrmService.logout();
    setIsAuthenticated(false);
    setContacts([]);
    setLeads([]);
    setDeals([]);
    setStats({
      totalContacts: 0,
      totalLeads: 0,
      totalDeals: 0,
      totalRevenue: 0
    });
  };

  const loadAllData = async () => {
    setIsLoading(true);
    try {
      await Promise.all([
        loadContacts(),
        loadLeads(),
        loadDeals()
      ]);
    } catch (error) {
      console.error('Error loading data:', error);
      setError('Failed to load CRM data. Please try refreshing.');
    } finally {
      setIsLoading(false);
    }
  };

  const loadContacts = async () => {
    try {
      const response = await zohoCrmService.getContacts();
      if (response.data) {
        setContacts(response.data);
        setStats(prev => ({ ...prev, totalContacts: response.data.length }));
      }
    } catch (error) {
      console.error('Error loading contacts:', error);
      if (error instanceof Error && error.message === 'Authentication expired') {
        setIsAuthenticated(false);
      }
    }
  };

  const loadLeads = async () => {
    try {
      const response = await zohoCrmService.getLeads();
      if (response.data) {
        setLeads(response.data);
        setStats(prev => ({ ...prev, totalLeads: response.data.length }));
      }
    } catch (error) {
      console.error('Error loading leads:', error);
      if (error instanceof Error && error.message === 'Authentication expired') {
        setIsAuthenticated(false);
      }
    }
  };

  const loadDeals = async () => {
    try {
      const response = await zohoCrmService.getDeals();
      if (response.data) {
        setDeals(response.data);
        const totalRevenue = response.data.reduce((sum: number, deal: any) => sum + (deal.Amount || 0), 0);
        setStats(prev => ({ 
          ...prev, 
          totalDeals: response.data.length,
          totalRevenue 
        }));
      }
    } catch (error) {
      console.error('Error loading deals:', error);
      if (error instanceof Error && error.message === 'Authentication expired') {
        setIsAuthenticated(false);
      }
    }
  };

  const refreshData = async () => {
    await loadAllData();
  };

  const getStatusColor = (status: string) => {
    switch (status?.toLowerCase()) {
      case 'qualified': return 'success';
      case 'working': return 'warning';
      case 'new': return 'info';
      default: return 'default';
    }
  };

  const getStageColor = (stage: string) => {
    switch (stage?.toLowerCase()) {
      case 'closed won': return 'success';
      case 'proposal': return 'info';
      case 'negotiation': return 'warning';
      default: return 'default';
    }
  };

  const filteredContacts = contacts.filter(contact =>
    contact.First_Name.toLowerCase().includes(contactSearch.toLowerCase()) ||
    contact.Last_Name.toLowerCase().includes(contactSearch.toLowerCase()) ||
    contact.Email.toLowerCase().includes(contactSearch.toLowerCase())
  );

  const filteredLeads = leads.filter(lead =>
    lead.First_Name.toLowerCase().includes(leadSearch.toLowerCase()) ||
    lead.Last_Name.toLowerCase().includes(leadSearch.toLowerCase()) ||
    lead.Company.toLowerCase().includes(leadSearch.toLowerCase())
  );

  const filteredDeals = deals.filter(deal =>
    deal.Deal_Name.toLowerCase().includes(dealSearch.toLowerCase()) ||
    deal.Account_Name.toLowerCase().includes(dealSearch.toLowerCase())
  );

  if (!isAuthenticated) {
    // Check if we're in the middle of OAuth callback processing
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get('code');
    
    if (code && isLoading) {
      return (
        <Box sx={{ p: 3, display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh' }}>
          <Card sx={{ p: 4, textAlign: 'center' }}>
            <CircularProgress size={60} sx={{ mb: 2 }} />
            <Typography variant="h6" gutterBottom>
              Connecting to Zoho CRM...
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Please wait while we complete the authentication process.
            </Typography>
          </Card>
        </Box>
      );
    }

    return (
      <Box sx={{ p: 3 }}>
        {/* Header */}
        <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box>
            <Typography variant="h4" sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 1 }}>
              <Business color="primary" />
              Zoho CRM Integration
            </Typography>
            <Typography variant="body1" color="text.secondary">
              Manage your customer relationships seamlessly within MangOS
            </Typography>
          </Box>
        </Box>

        {/* Authentication Required Card */}
        <Card sx={{ maxWidth: 600, mx: 'auto', mt: 4 }}>
          <CardContent sx={{ textAlign: 'center', p: 4 }}>
            <Business sx={{ fontSize: 64, color: 'primary.main', mb: 2 }} />
            <Typography variant="h5" gutterBottom>
              Authentication Required
            </Typography>
            <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
              To access Zoho CRM features, you need to connect your Zoho account with MangOS.
            </Typography>
            
            <Box sx={{ textAlign: 'left', mb: 3 }}>
              <Typography variant="h6" gutterBottom>Features:</Typography>
              <ul>
                <li>Secure OAuth 2.0 authentication</li>
                <li>Access to your Contacts, Leads, and Deals</li>
                <li>Real-time synchronization</li>
                <li>Full CRUD operations</li>
              </ul>
            </Box>

            <Button
              variant="contained"
              size="large"
              startIcon={isLoading ? <CircularProgress size={20} color="inherit" /> : <Link />}
              onClick={connectToZoho}
              disabled={isLoading}
              sx={{ mt: 2 }}
            >
              {isLoading ? 'Connecting...' : 'Connect to Zoho CRM'}
            </Button>
          </CardContent>
        </Card>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      {/* Header */}
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Box>
          <Typography variant="h4" sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 1 }}>
            <Business color="primary" />
            Zoho CRM Integration
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Manage your customer relationships seamlessly within MangOS
          </Typography>
        </Box>
        
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button
            variant="outlined"
            startIcon={<Refresh />}
            onClick={refreshData}
            disabled={isLoading}
          >
            Refresh
          </Button>
          <Button
            variant="outlined"
            color="error"
            startIcon={<LinkOff />}
            onClick={disconnect}
          >
            Disconnect
          </Button>
        </Box>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      {/* Statistics Cards */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <PersonAdd color="primary" sx={{ fontSize: 40 }} />
                <Box>
                  <Typography variant="h4">{stats.totalContacts}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    Total Contacts
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <PersonAdd color="warning" sx={{ fontSize: 40 }} />
                <Box>
                  <Typography variant="h4">{stats.totalLeads}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    Active Leads
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <Handshake color="success" sx={{ fontSize: 40 }} />
                <Box>
                  <Typography variant="h4">{stats.totalDeals}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    Open Deals
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
        
        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <AttachMoney color="error" sx={{ fontSize: 40 }} />
                <Box>
                  <Typography variant="h4">${stats.totalRevenue.toLocaleString()}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    Total Revenue
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Tabs */}
      <Card>
        <Tabs value={selectedTab} onChange={(_, newValue) => setSelectedTab(newValue)}>
          <Tab label={`Contacts (${stats.totalContacts})`} />
          <Tab label={`Leads (${stats.totalLeads})`} />
          <Tab label={`Deals (${stats.totalDeals})`} />
        </Tabs>

        {/* Contacts Tab */}
        {selectedTab === 0 && (
          <CardContent>
            <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <TextField
                placeholder="Search contacts..."
                value={contactSearch}
                onChange={(e) => setContactSearch(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <Search />
                    </InputAdornment>
                  ),
                }}
                sx={{ width: 300 }}
              />
              <Button variant="contained" startIcon={<PersonAdd />}>
                Add Contact
              </Button>
            </Box>

            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Name</TableCell>
                    <TableCell>Email</TableCell>
                    <TableCell>Phone</TableCell>
                    <TableCell>Company</TableCell>
                    <TableCell>Created</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {filteredContacts.map((contact) => (
                    <TableRow key={contact.id}>
                      <TableCell>{`${contact.First_Name} ${contact.Last_Name}`}</TableCell>
                      <TableCell>{contact.Email}</TableCell>
                      <TableCell>{contact.Phone || 'N/A'}</TableCell>
                      <TableCell>{contact.Account_Name || 'N/A'}</TableCell>
                      <TableCell>
                        {contact.Created_Time ? new Date(contact.Created_Time).toLocaleDateString() : 'N/A'}
                      </TableCell>
                      <TableCell>
                        <IconButton size="small" color="primary">
                          <Edit />
                        </IconButton>
                        <IconButton size="small" color="error">
                          <Delete />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        )}

        {/* Leads Tab */}
        {selectedTab === 1 && (
          <CardContent>
            <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <TextField
                placeholder="Search leads..."
                value={leadSearch}
                onChange={(e) => setLeadSearch(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <Search />
                    </InputAdornment>
                  ),
                }}
                sx={{ width: 300 }}
              />
              <Button variant="contained" startIcon={<PersonAdd />}>
                Add Lead
              </Button>
            </Box>

            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Name</TableCell>
                    <TableCell>Email</TableCell>
                    <TableCell>Company</TableCell>
                    <TableCell>Status</TableCell>
                    <TableCell>Created</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {filteredLeads.map((lead) => (
                    <TableRow key={lead.id}>
                      <TableCell>{`${lead.First_Name} ${lead.Last_Name}`}</TableCell>
                      <TableCell>{lead.Email}</TableCell>
                      <TableCell>{lead.Company}</TableCell>
                      <TableCell>
                        <Chip 
                          label={lead.Lead_Status || 'New'} 
                          color={getStatusColor(lead.Lead_Status || 'new')}
                          size="small"
                        />
                      </TableCell>
                      <TableCell>
                        {lead.Created_Time ? new Date(lead.Created_Time).toLocaleDateString() : 'N/A'}
                      </TableCell>
                      <TableCell>
                        <IconButton size="small" color="primary">
                          <Edit />
                        </IconButton>
                        <IconButton size="small" color="success">
                          <Handshake />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        )}

        {/* Deals Tab */}
        {selectedTab === 2 && (
          <CardContent>
            <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <TextField
                placeholder="Search deals..."
                value={dealSearch}
                onChange={(e) => setDealSearch(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <Search />
                    </InputAdornment>
                  ),
                }}
                sx={{ width: 300 }}
              />
              <Button variant="contained" startIcon={<Handshake />}>
                Add Deal
              </Button>
            </Box>

            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Deal Name</TableCell>
                    <TableCell>Account</TableCell>
                    <TableCell>Stage</TableCell>
                    <TableCell>Amount</TableCell>
                    <TableCell>Closing Date</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {filteredDeals.map((deal) => (
                    <TableRow key={deal.id}>
                      <TableCell>{deal.Deal_Name}</TableCell>
                      <TableCell>{deal.Account_Name}</TableCell>
                      <TableCell>
                        <Chip 
                          label={deal.Stage} 
                          color={getStageColor(deal.Stage)}
                          size="small"
                        />
                      </TableCell>
                      <TableCell sx={{ fontWeight: 'bold', color: 'success.main' }}>
                        ${deal.Amount.toLocaleString()}
                      </TableCell>
                      <TableCell>{new Date(deal.Closing_Date).toLocaleDateString()}</TableCell>
                      <TableCell>
                        <IconButton size="small" color="primary">
                          <Edit />
                        </IconButton>
                        <IconButton size="small" color="info">
                          <Business />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        )}
      </Card>
    </Box>
  );
};

export default ZohoCRM;
